services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "6543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uv run fastapi dev --host 0.0.0.0

volumes:
  postgres_data:
